=== Grzybo/Game-Test-Studio/GameTestStudio/src/main/java/net/sourceforge/jsptabcontrol/resources/jsptabcontrol-config-1.0.dtd
<!-- JSPTabControlConfig DTD.

<!DOCTYPE jsptabcontrol-config PUBLIC 
    "-//JSPTabControl/JSPTabControl JSPTabControlConfig DTD 1.0//EN"
    "http://jsptabcontrol.sourceforge.net/dtd/jsptabcontrol-config-1.0.dtd">
-->

<!--
	The document root.
 -->

<!ELEMENT jsptabcontrol-config (
	tabpage-states
)>
	
<!--
	TABPAGE-STATES element definition; define tabpage-state for each States.
-->
<!ELEMENT tabpage-states (tabpage-state*)>

<!--
	TABPAGE-STATE element definition; define a tabpage-state for a state.
-->
<!ELEMENT tabpage-state (insert-styleclass*,insert-javascript*)>
	<!ATTLIST tabpage-state name CDATA #REQUIRED>	
	<!ATTLIST tabpage-state visible (true|false) #IMPLIED>	

<!--
	INSERT-STYLECLASS element definition; define a style class to insert to 
	tabPageHeader or tabPageBody (where).
-->
<!ELEMENT insert-styleclass ANY>
	<!ATTLIST insert-styleclass where CDATA #REQUIRED>

<!--
	INSERT-JAVASCRIPT element definition; define an javascript content
	to insert for an event into A HREF of tab page Header.
-->
<!ELEMENT insert-javascript ANY>
	<!ATTLIST insert-javascript event CDATA #REQUIRED>
	<!ATTLIST insert-javascript where (before|after) #IMPLIED>

=== Grzybo/Game-Test-Studio/GameTestStudio/src/main/webapp/WEB-INF/jsptabcontrol-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jsptabcontrol-config PUBLIC 
    "-//JSPTabControl/JSPTabControl JSPTabControlConfig DTD 1.0//EN"
    "http://jsptabcontrol.sourceforge.net/dtd/jsptabcontrol-config-1.0.dtd">
<jsptabcontrol-config>
	<tabpage-states>		
	
		<!-- Render of Tab page with DISABLE state -->
		<tabpage-state name="READ-ONLY">	
			<insert-styleclass where="tabPageHeader" >
				<![CDATA[tabPageHeaderReadOnly]]>
			</insert-styleclass>	
			<insert-styleclass where="tabPageBody" >
				<![CDATA[tabPageBodyReadOnly]]>
			</insert-styleclass>	
		</tabpage-state>

		<!-- Render of Tab page with FORBIDDEN state -->
		<tabpage-state name="FORBIDDEN">	
			<insert-styleclass where="tabPageHeader" >
				<![CDATA[tabPageHeaderForbidden]]>
			</insert-styleclass>	
			<insert-styleclass where="tabPageBody" >
				<![CDATA[tabPageBodyForbidden]]>
			</insert-styleclass>				
			<insert-javascript event="onclick" where="before" >
				<![CDATA[alert('You are not authorized to select this tab page!');return false;]]>
			</insert-javascript>
		</tabpage-state>

		<!-- Render of Tab page with INVISIBLE state -->
		<tabpage-state name="INVISIBLE" visible="false" >	
			
		</tabpage-state>
				
	</tabpage-states>
	
</jsptabcontrol-config>
